### ISSUE TITLE
Icons missing even if importing the MapBox css from its CDN source

### ISSUE THREAD

**Issue by calebeaires** [soal/vue-mapbox#164]
My code is built on top of vue-cli. I have imported css on public.html file. But every image (data:image/svg+xml ....) retrieved within the MapBox css does not apear on the map. 

```html
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css' rel='stylesheet' />
```

```css
.mapboxgl-ctrl-icon.mapboxgl-ctrl-compass > .mapboxgl-ctrl-compass-arrow {
  width: 20px;
  height: 20px;
  margin: 5px;
  background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox='0 0 20 20' xmlns='http://www.w3.org/2000/svg'%3E %3Cpolygon fill='%23333333' points='6,9 10,1 14,9'/%3E %3Cpolygon fill='%23CCCCCC' points='6,11 10,19 14,11 '/%3E %3C/svg%3E");
  background-repeat: no-repeat;
  display: inline-block;
}
```

Icons missing:

![Captura de Tela 2020-01-24 às 22 42 09](https://user-images.githubusercontent.com/794195/73114606-d258c300-3efa-11ea-8115-d9cbb35bc2e0.png)
